# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001Values(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, temperature: float=None, humidity: float=None, time: str=None):  # noqa: E501
        """InlineResponse2001Values - a model defined in Swagger

        :param temperature: The temperature of this InlineResponse2001Values.  # noqa: E501
        :type temperature: float
        :param humidity: The humidity of this InlineResponse2001Values.  # noqa: E501
        :type humidity: float
        :param time: The time of this InlineResponse2001Values.  # noqa: E501
        :type time: str
        """
        self.swagger_types = {
            'temperature': float,
            'humidity': float,
            'time': str
        }

        self.attribute_map = {
            'temperature': 'temperature',
            'humidity': 'humidity',
            'time': 'time'
        }
        self._temperature = temperature
        self._humidity = humidity
        self._time = time

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001Values':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_values of this InlineResponse2001Values.  # noqa: E501
        :rtype: InlineResponse2001Values
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> float:
        """Gets the temperature of this InlineResponse2001Values.


        :return: The temperature of this InlineResponse2001Values.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this InlineResponse2001Values.


        :param temperature: The temperature of this InlineResponse2001Values.
        :type temperature: float
        """

        self._temperature = temperature

    @property
    def humidity(self) -> float:
        """Gets the humidity of this InlineResponse2001Values.


        :return: The humidity of this InlineResponse2001Values.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this InlineResponse2001Values.


        :param humidity: The humidity of this InlineResponse2001Values.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def time(self) -> str:
        """Gets the time of this InlineResponse2001Values.


        :return: The time of this InlineResponse2001Values.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this InlineResponse2001Values.


        :param time: The time of this InlineResponse2001Values.
        :type time: str
        """

        self._time = time
