# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_position import InlineResponse2001Position  # noqa: F401,E501
from swagger_server.models.inline_response2001_values import InlineResponse2001Values  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, values: List[InlineResponse2001Values]=None, position: List[InlineResponse2001Position]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param values: The values of this InlineResponse2001.  # noqa: E501
        :type values: List[InlineResponse2001Values]
        :param position: The position of this InlineResponse2001.  # noqa: E501
        :type position: List[InlineResponse2001Position]
        """
        self.swagger_types = {
            'values': List[InlineResponse2001Values],
            'position': List[InlineResponse2001Position]
        }

        self.attribute_map = {
            'values': 'values',
            'position': 'position'
        }
        self._values = values
        self._position = position

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def values(self) -> List[InlineResponse2001Values]:
        """Gets the values of this InlineResponse2001.


        :return: The values of this InlineResponse2001.
        :rtype: List[InlineResponse2001Values]
        """
        return self._values

    @values.setter
    def values(self, values: List[InlineResponse2001Values]):
        """Sets the values of this InlineResponse2001.


        :param values: The values of this InlineResponse2001.
        :type values: List[InlineResponse2001Values]
        """

        self._values = values

    @property
    def position(self) -> List[InlineResponse2001Position]:
        """Gets the position of this InlineResponse2001.


        :return: The position of this InlineResponse2001.
        :rtype: List[InlineResponse2001Position]
        """
        return self._position

    @position.setter
    def position(self, position: List[InlineResponse2001Position]):
        """Sets the position of this InlineResponse2001.


        :param position: The position of this InlineResponse2001.
        :type position: List[InlineResponse2001Position]
        """

        self._position = position
