# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_user import BaseUser  # noqa: F401,E501
from swagger_server import util


class PatchUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, email: str=None, password: str=None, is_active: bool=None, last_login: datetime=None):  # noqa: E501
        """PatchUser - a model defined in Swagger

        :param username: The username of this PatchUser.  # noqa: E501
        :type username: str
        :param email: The email of this PatchUser.  # noqa: E501
        :type email: str
        :param password: The password of this PatchUser.  # noqa: E501
        :type password: str
        :param is_active: The is_active of this PatchUser.  # noqa: E501
        :type is_active: bool
        :param last_login: The last_login of this PatchUser.  # noqa: E501
        :type last_login: datetime
        """
        self.swagger_types = {
            'username': str,
            'email': str,
            'password': str,
            'is_active': bool,
            'last_login': datetime
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'password': 'password',
            'is_active': 'is_active',
            'last_login': 'last_login'
        }
        self._username = username
        self._email = email
        self._password = password
        self._is_active = is_active
        self._last_login = last_login

    @classmethod
    def from_dict(cls, dikt) -> 'PatchUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patchUser of this PatchUser.  # noqa: E501
        :rtype: PatchUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this PatchUser.


        :return: The username of this PatchUser.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this PatchUser.


        :param username: The username of this PatchUser.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this PatchUser.


        :return: The email of this PatchUser.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this PatchUser.


        :param email: The email of this PatchUser.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this PatchUser.


        :return: The password of this PatchUser.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this PatchUser.


        :param password: The password of this PatchUser.
        :type password: str
        """

        self._password = password

    @property
    def is_active(self) -> bool:
        """Gets the is_active of this PatchUser.


        :return: The is_active of this PatchUser.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active: bool):
        """Sets the is_active of this PatchUser.


        :param is_active: The is_active of this PatchUser.
        :type is_active: bool
        """

        self._is_active = is_active

    @property
    def last_login(self) -> datetime:
        """Gets the last_login of this PatchUser.


        :return: The last_login of this PatchUser.
        :rtype: datetime
        """
        return self._last_login

    @last_login.setter
    def last_login(self, last_login: datetime):
        """Sets the last_login of this PatchUser.


        :param last_login: The last_login of this PatchUser.
        :type last_login: datetime
        """

        self._last_login = last_login
